/* toml-vala.h generated by valac 0.56.18, the Vala compiler, do not modify */

#ifndef __SRC_TOML_VALA_H__
#define __SRC_TOML_VALA_H__

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <float.h>
#include <math.h>
#include <gee.h>
#include <gio/gio.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum  {
	TOML_TYPE_STRING,
	TOML_TYPE_INT,
	TOML_TYPE_FLOAT,
	TOML_TYPE_BOOL,
	TOML_TYPE_DATETIME,
	TOML_TYPE_ARRAY,
	TOML_TYPE_TABLE
} TomlType;

#define TYPE_TOML_TYPE (toml_type_get_type ())

#define TYPE_TOML_VALUE (toml_value_get_type ())
#define TOML_VALUE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOML_VALUE, TomlValue))
#define TOML_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOML_VALUE, TomlValueClass))
#define IS_TOML_VALUE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOML_VALUE))
#define IS_TOML_VALUE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOML_VALUE))
#define TOML_VALUE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOML_VALUE, TomlValueClass))

typedef struct _TomlValue TomlValue;
typedef struct _TomlValueClass TomlValueClass;
typedef struct _TomlValuePrivate TomlValuePrivate;

#define TYPE_TOML_ERROR (toml_error_get_type ())

#define TYPE_TOML_PARSER (toml_parser_get_type ())
#define TOML_PARSER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOML_PARSER, TomlParser))
#define TOML_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOML_PARSER, TomlParserClass))
#define IS_TOML_PARSER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOML_PARSER))
#define IS_TOML_PARSER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOML_PARSER))
#define TOML_PARSER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOML_PARSER, TomlParserClass))

typedef struct _TomlParser TomlParser;
typedef struct _TomlParserClass TomlParserClass;
typedef struct _TomlParserPrivate TomlParserPrivate;

#define TYPE_TOML_WATCHER (toml_watcher_get_type ())
#define TOML_WATCHER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOML_WATCHER, TomlWatcher))
#define TOML_WATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOML_WATCHER, TomlWatcherClass))
#define IS_TOML_WATCHER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOML_WATCHER))
#define IS_TOML_WATCHER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOML_WATCHER))
#define TOML_WATCHER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOML_WATCHER, TomlWatcherClass))

typedef struct _TomlWatcher TomlWatcher;
typedef struct _TomlWatcherClass TomlWatcherClass;
typedef struct _TomlWatcherPrivate TomlWatcherPrivate;

#define TYPE_TOML_VALIDATION_ERROR (toml_validation_error_get_type ())
#define TOML_VALIDATION_ERROR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOML_VALIDATION_ERROR, TomlValidationError))
#define TOML_VALIDATION_ERROR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOML_VALIDATION_ERROR, TomlValidationErrorClass))
#define IS_TOML_VALIDATION_ERROR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOML_VALIDATION_ERROR))
#define IS_TOML_VALIDATION_ERROR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOML_VALIDATION_ERROR))
#define TOML_VALIDATION_ERROR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOML_VALIDATION_ERROR, TomlValidationErrorClass))

typedef struct _TomlValidationError TomlValidationError;
typedef struct _TomlValidationErrorClass TomlValidationErrorClass;
typedef struct _TomlValidationErrorPrivate TomlValidationErrorPrivate;

#define TYPE_TOML_VALIDATOR (toml_validator_get_type ())
#define TOML_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_TOML_VALIDATOR, TomlValidator))
#define TOML_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_TOML_VALIDATOR, TomlValidatorClass))
#define IS_TOML_VALIDATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_TOML_VALIDATOR))
#define IS_TOML_VALIDATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_TOML_VALIDATOR))
#define TOML_VALIDATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_TOML_VALIDATOR, TomlValidatorClass))

typedef struct _TomlValidator TomlValidator;
typedef struct _TomlValidatorClass TomlValidatorClass;
typedef struct _TomlValidatorPrivate TomlValidatorPrivate;

struct _TomlValue {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomlValuePrivate * priv;
};

struct _TomlValueClass {
	GTypeClass parent_class;
	void (*finalize) (TomlValue *self);
};

typedef enum  {
	TOML_ERROR_INVALID_SYNTAX,
	TOML_ERROR_INVALID_VALUE,
	TOML_ERROR_DUPLICATE_KEY,
	TOML_ERROR_MISSING_KEY
} TomlError;
#define TOML_ERROR toml_error_quark ()

struct _TomlParser {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomlParserPrivate * priv;
};

struct _TomlParserClass {
	GTypeClass parent_class;
	void (*finalize) (TomlParser *self);
};

struct _TomlWatcher {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomlWatcherPrivate * priv;
};

struct _TomlWatcherClass {
	GTypeClass parent_class;
	void (*finalize) (TomlWatcher *self);
};

struct _TomlValidationError {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomlValidationErrorPrivate * priv;
};

struct _TomlValidationErrorClass {
	GTypeClass parent_class;
	void (*finalize) (TomlValidationError *self);
};

struct _TomlValidator {
	GTypeInstance parent_instance;
	volatile int ref_count;
	TomlValidatorPrivate * priv;
};

struct _TomlValidatorClass {
	GTypeClass parent_class;
	void (*finalize) (TomlValidator *self);
};

VALA_EXTERN GType toml_type_get_type (void) G_GNUC_CONST ;
VALA_EXTERN gpointer toml_value_ref (gpointer instance);
VALA_EXTERN void toml_value_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_toml_value (const gchar* name,
                                   const gchar* nick,
                                   const gchar* blurb,
                                   GType object_type,
                                   GParamFlags flags);
VALA_EXTERN void value_set_toml_value (GValue* value,
                           gpointer v_object);
VALA_EXTERN void value_take_toml_value (GValue* value,
                            gpointer v_object);
VALA_EXTERN gpointer value_get_toml_value (const GValue* value);
VALA_EXTERN GType toml_value_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TomlValue, toml_value_unref)
VALA_EXTERN TomlValue* toml_value_new_string (const gchar* val);
VALA_EXTERN TomlValue* toml_value_construct_string (GType object_type,
                                        const gchar* val);
VALA_EXTERN TomlValue* toml_value_new_int (gint64 val);
VALA_EXTERN TomlValue* toml_value_construct_int (GType object_type,
                                     gint64 val);
VALA_EXTERN TomlValue* toml_value_new_float (gdouble val);
VALA_EXTERN TomlValue* toml_value_construct_float (GType object_type,
                                       gdouble val);
VALA_EXTERN TomlValue* toml_value_new_bool (gboolean val);
VALA_EXTERN TomlValue* toml_value_construct_bool (GType object_type,
                                      gboolean val);
VALA_EXTERN TomlValue* toml_value_new_datetime (const gchar* val);
VALA_EXTERN TomlValue* toml_value_construct_datetime (GType object_type,
                                          const gchar* val);
VALA_EXTERN TomlValue* toml_value_new_array (GeeArrayList* val);
VALA_EXTERN TomlValue* toml_value_construct_array (GType object_type,
                                       GeeArrayList* val);
VALA_EXTERN TomlValue* toml_value_new_table (GeeHashMap* val);
VALA_EXTERN TomlValue* toml_value_construct_table (GType object_type,
                                       GeeHashMap* val);
VALA_EXTERN TomlValue* toml_value_get (TomlValue* self,
                           const gchar* key);
VALA_EXTERN TomlValue* toml_value_get_index (TomlValue* self,
                                 gint index);
VALA_EXTERN gchar* toml_value_to_toml (TomlValue* self);
VALA_EXTERN gchar* toml_value_to_json (TomlValue* self);
VALA_EXTERN GQuark toml_error_quark (void);
VALA_EXTERN GType toml_error_get_type (void) G_GNUC_CONST ;
VALA_EXTERN TomlValue* toml_value_from_json (const gchar* json,
                                 GError** error);
VALA_EXTERN TomlValue* toml_value_new (void);
VALA_EXTERN TomlValue* toml_value_construct (GType object_type);
VALA_EXTERN TomlType toml_value_get_val_type (TomlValue* self);
VALA_EXTERN const gchar* toml_value_get_string_val (TomlValue* self);
VALA_EXTERN gint64 toml_value_get_int_val (TomlValue* self);
VALA_EXTERN gdouble toml_value_get_float_val (TomlValue* self);
VALA_EXTERN gboolean toml_value_get_bool_val (TomlValue* self);
VALA_EXTERN GeeArrayList* toml_value_get_array_val (TomlValue* self);
VALA_EXTERN GeeHashMap* toml_value_get_table_val (TomlValue* self);
VALA_EXTERN gpointer toml_parser_ref (gpointer instance);
VALA_EXTERN void toml_parser_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_toml_parser (const gchar* name,
                                    const gchar* nick,
                                    const gchar* blurb,
                                    GType object_type,
                                    GParamFlags flags);
VALA_EXTERN void value_set_toml_parser (GValue* value,
                            gpointer v_object);
VALA_EXTERN void value_take_toml_parser (GValue* value,
                             gpointer v_object);
VALA_EXTERN gpointer value_get_toml_parser (const GValue* value);
VALA_EXTERN GType toml_parser_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TomlParser, toml_parser_unref)
VALA_EXTERN TomlParser* toml_parser_new (const gchar* toml);
VALA_EXTERN TomlParser* toml_parser_construct (GType object_type,
                                   const gchar* toml);
VALA_EXTERN TomlValue* toml_parser_parse_file (const gchar* filename,
                                   const gchar* encoding,
                                   GError** error);
VALA_EXTERN void toml_parser_parse_file_async (const gchar* filename,
                                   const gchar* encoding,
                                   GAsyncReadyCallback _callback_,
                                   gpointer _user_data_);
VALA_EXTERN TomlValue* toml_parser_parse_file_finish (GAsyncResult* _res_,
                                          GError** error);
VALA_EXTERN TomlValue* toml_parser_parse (TomlParser* self,
                              GError** error);
VALA_EXTERN gpointer toml_watcher_ref (gpointer instance);
VALA_EXTERN void toml_watcher_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_toml_watcher (const gchar* name,
                                     const gchar* nick,
                                     const gchar* blurb,
                                     GType object_type,
                                     GParamFlags flags);
VALA_EXTERN void value_set_toml_watcher (GValue* value,
                             gpointer v_object);
VALA_EXTERN void value_take_toml_watcher (GValue* value,
                              gpointer v_object);
VALA_EXTERN gpointer value_get_toml_watcher (const GValue* value);
VALA_EXTERN GType toml_watcher_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TomlWatcher, toml_watcher_unref)
VALA_EXTERN TomlWatcher* toml_watcher_new (const gchar* filename);
VALA_EXTERN TomlWatcher* toml_watcher_construct (GType object_type,
                                     const gchar* filename);
VALA_EXTERN void toml_watcher_start (TomlWatcher* self,
                         GError** error);
VALA_EXTERN void toml_watcher_stop (TomlWatcher* self);
VALA_EXTERN gpointer toml_validation_error_ref (gpointer instance);
VALA_EXTERN void toml_validation_error_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_toml_validation_error (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
VALA_EXTERN void value_set_toml_validation_error (GValue* value,
                                      gpointer v_object);
VALA_EXTERN void value_take_toml_validation_error (GValue* value,
                                       gpointer v_object);
VALA_EXTERN gpointer value_get_toml_validation_error (const GValue* value);
VALA_EXTERN GType toml_validation_error_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TomlValidationError, toml_validation_error_unref)
VALA_EXTERN TomlValidationError* toml_validation_error_new (const gchar* msg,
                                                gint l,
                                                gint c,
                                                const gchar* sugg);
VALA_EXTERN TomlValidationError* toml_validation_error_construct (GType object_type,
                                                      const gchar* msg,
                                                      gint l,
                                                      gint c,
                                                      const gchar* sugg);
VALA_EXTERN const gchar* toml_validation_error_get_message (TomlValidationError* self);
VALA_EXTERN gint toml_validation_error_get_line (TomlValidationError* self);
VALA_EXTERN gint toml_validation_error_get_col (TomlValidationError* self);
VALA_EXTERN const gchar* toml_validation_error_get_suggestion (TomlValidationError* self);
VALA_EXTERN gpointer toml_validator_ref (gpointer instance);
VALA_EXTERN void toml_validator_unref (gpointer instance);
VALA_EXTERN GParamSpec* param_spec_toml_validator (const gchar* name,
                                       const gchar* nick,
                                       const gchar* blurb,
                                       GType object_type,
                                       GParamFlags flags);
VALA_EXTERN void value_set_toml_validator (GValue* value,
                               gpointer v_object);
VALA_EXTERN void value_take_toml_validator (GValue* value,
                                gpointer v_object);
VALA_EXTERN gpointer value_get_toml_validator (const GValue* value);
VALA_EXTERN GType toml_validator_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (TomlValidator, toml_validator_unref)
VALA_EXTERN GeeArrayList* toml_validator_validate_file (const gchar* filename,
                                            const gchar* encoding);
VALA_EXTERN TomlValidator* toml_validator_new (void);
VALA_EXTERN TomlValidator* toml_validator_construct (GType object_type);

G_END_DECLS

#endif
